[package]
name = "erreport"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = ""
keywords = []
documentation = "https://docs.rs/erreport"
repository = "https://github.com/qdwang/erreport"

[dependencies]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
